### ISSUE TITLE
后台报错

### ISSUE THREAD

**Issue by 3944Realms** [CSneko/toNeko#10]
- [x] 前置最新版本0.8

[18:01:51 ERROR]: Could not pass event EntityDamageByEntityEvent to toNeko v0.0.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null
        at com.crystalneko.toneko.event.PlayerAttack.onPlayerAttack(PlayerAttack.java:54) ~[toNeko-0.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2086]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-
2086]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[purpur-1.20.2.jar:git-Purpur-2086
]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255) ~[purpur-1.20.2.jar:gi
t-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1108) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289) ~[purpur-1.20.
2.jar:git-Purpur-2086]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2291) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1105) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1511) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1012) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1162) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1365) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2849) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2771) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1299) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:03:07 ERROR]: Could not pass event EntityDamageByEntityEvent to toNeko v0.0.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null
        at com.crystalneko.toneko.event.PlayerAttack.onPlayerAttack(PlayerAttack.java:54) ~[toNeko-0.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2086]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-
2086]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[purpur-1.20.2.jar:git-Purpur-2086
]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255) ~[purpur-1.20.2.jar:gi
t-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1108) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289) ~[purpur-1.20.
2.jar:git-Purpur-2086]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2291) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1105) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1511) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1012) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1162) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1365) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2849) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2771) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1437) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[18:03:11 ERROR]: Could not pass event EntityDamageByEntityEvent to toNeko v0.0.8
java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.meta.ItemMeta.getPersistentDataContainer()" because "itemMeta" is null
        at com.crystalneko.toneko.event.PlayerAttack.onPlayerAttack(PlayerAttack.java:54) ~[toNeko-0.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor175.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2086]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-
2086]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEvent(CraftEventFactory.java:266) ~[purpur-1.20.2.jar:git-Purpur-2086
]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1255) ~[purpur-1.20.2.jar:gi
t-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1108) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1051) ~[purpur-1.20.2.jar:
git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1289) ~[purpur-1.20.
2.jar:git-Purpur-2086]
        at net.minecraft.world.entity.LivingEntity.damageEntity0(LivingEntity.java:2291) ~[?:?]
        at net.minecraft.world.entity.player.Player.damageEntity0(Player.java:1105) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1511) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:1012) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:1162) ~[?:?]
        at net.minecraft.world.entity.player.Player.attack(Player.java:1365) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.attack(ServerPlayer.java:2307) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl$4.a(ServerGamePacketListenerImpl.java:2849) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket$1.dispatch(ServerboundInteractPacket.java:24) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.dispatch(ServerboundInteractPacket.java:80) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleInteract(ServerGamePacketListenerImpl.java:2771) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:67) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundInteractPacket.handle(ServerboundInteractPacket.java:12) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:53) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1351) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:193) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1328) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1321) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1437) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]

**Comment by CSneko** [comment]
前置确实是最新的，但你的插件版本貌似不是最新的，从报错可以看出，你的版本是0.0.8,而最新版本是0.0.9
