### ISSUE TITLE
[BUG]在Leaves 1.20.4上报错

### ISSUE THREAD

**Issue by MF-Dust** [CSneko/toNeko#24]
[08:22:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'toneko:neko' in plugin toNeko v0.2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1004) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2240) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1333) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1222) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at com.crystalneko.toneko.command.NekoCommand.onCommand(NekoCommand.java:27) ~[[玩法][猫娘]toNeko-0.2.3.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**Comment by MrHua269** [comment]
已经在pr https://github.com/CSneko/toNeko/pull/26 中修复()

**Comment by w2w2e2wq** [comment]
自己构建之后,问题仍然出现:
[17:31:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'toneko' in plugin toNeko v0.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1004) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2240) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1540) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.crystalneko.toneko.command.ToNekoCommand.onCommand(ToNekoCommand.java:261) ~[[玩法][猫娘]toNeko-0.2.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more

**Comment by w2w2e2wq** [comment]
自己构建后,问题仍然出现:
[17:31:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'toneko' in plugin toNeko v0.2.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1004) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:434) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2240) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$14(ServerGamePacketListenerImpl.java:2200) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1450) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:189) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1427) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1355) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1540) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314) ~[leaves-1.20.4.jar:git-Leaves-"b7d40e0"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.crystalneko.toneko.command.ToNekoCommand.onCommand(ToNekoCommand.java:261) ~[[玩法][猫娘]toNeko-0.2.8.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[leaves-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        ... 29 more
