### ISSUE TITLE
[BUG] 在 Mohist 平台上未能成功加载 toNeko

### ISSUE THREAD

**Issue by SuoHouDaiShi** [CSneko/toNeko#40]
![图片](https://github.com/CSneko/toNeko/assets/119282947/32da5859-2e57-461d-b3ad-a5655d70207e)
报错：
```
[00:36:15 ERROR]: Error occurred while enabling toNeko v0.3.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
        at com.crystalneko.toneko.items.StickItemWrapper.wrapStickItemLevel2(StickItemWrapper.java:71) ~[?:?]
        at com.crystalneko.toneko.items.StickItemRecipeRegistry.registerRecipe(StickItemRecipeRegistry.java:14) ~[?:?]
        at com.crystalneko.toneko.ToNeko.onEnable(ToNeko.java:80) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:471) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:397) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:478) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:828) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
        at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:150) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:109) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 14 more
```
插件版本：
ctLib 0.1.5
toNeko 0.3.2

**Comment by CSneko** [comment]
将ctlib与toNeko均更新至最新版本试试

**Comment by SuoHouDaiShi** [comment]
```
2024-05-26 16:23:46,892 INFO  [Server thread] c.c.t.ToNeko.publish(36): [toNeko] Enabling toNeko v0.4.6
2024-05-26 16:23:46,917 INFO  [Server thread] Minecraft.publish(36): ctLib插件已启动！
2024-05-26 16:23:47,010 ERROR [Server thread] Minecraft.publish(32): Error occurred while enabling toNeko v0.4.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
	at com.crystalneko.toneko.items.StickItemWrapper.wrapStickItemLevel2(StickItemWrapper.java:75) ~[?:?]
	at com.crystalneko.toneko.items.StickItemRecipeRegistry.registerRecipe(StickItemRecipeRegistry.java:14) ~[?:?]
	at com.crystalneko.toneko.ToNeko.onEnable(ToNeko.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:471) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:397) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:478) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:828) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:150) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:109) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
2024-05-26 16:23:47,029 INFO  [Server thread] c.c.t.ToNeko.publish(36): [toNeko] Disabling toNeko v0.4.6
```
ctLib 和 toNeko 此时已为最新版本

**Comment by SuoHouDaiShi** [comment]
```
2024-05-26 16:23:46,892 INFO  [Server thread] c.c.t.ToNeko.publish(36): [toNeko] Enabling toNeko v0.4.6
2024-05-26 16:23:46,917 INFO  [Server thread] Minecraft.publish(36): ctLib插件已启动！
2024-05-26 16:23:47,010 ERROR [Server thread] Minecraft.publish(32): Error occurred while enabling toNeko v0.4.6 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/Component
	at com.crystalneko.toneko.items.StickItemWrapper.wrapStickItemLevel2(StickItemWrapper.java:75) ~[?:?]
	at com.crystalneko.toneko.items.StickItemRecipeRegistry.registerRecipe(StickItemRecipeRegistry.java:14) ~[?:?]
	at com.crystalneko.toneko.ToNeko.onEnable(ToNeko.java:80) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:471) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:397) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:7e29f765-296df566-9fb885e8]
	at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:478) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:368) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:220) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:828) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:287) ~[server-1.18.2-20220404.173914-srg.jar%23118!/:?]
	at java.lang.Thread.run(Thread.java:842) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.Component
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:150) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:109) ~[forge-1.18.2-40.2.17-universal.jar%23123!/:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 14 more
2024-05-26 16:23:47,029 INFO  [Server thread] c.c.t.ToNeko.publish(36): [toNeko] Disabling toNeko v0.4.6
```
ctLib 和 toNeko 此时已为最新版本

**Comment by CSneko** [comment]
了解
