### ISSUE TITLE
1.21.1游戏启动时崩溃

### ISSUE THREAD

**Issue by Lemonfeline** [CSneko/toNeko#67]
[minecraft-exported-crash-info-2024-12-16T20-04-14.zip](https://github.com/user-attachments/files/18149776/minecraft-exported-crash-info-2024-12-16T20-04-14.zip)

只装了必需的模组，启动器版本 HMCL v3.5.8，不安装toneko可以正常启动
![图片](https://github.com/user-attachments/assets/0964fe1a-e755-4bfb-a551-16ebcfdc4435)

崩溃报告
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2024-12-16 20:04:10
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'toneko' at 'org.cneko.toneko.fabric.ToNeko'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ExceptionInInitializerError
	at knot//org.cneko.toneko.fabric.entities.ToNekoEntities.init(ToNekoEntities.java:61)
	at knot//org.cneko.toneko.fabric.ToNeko.onInitialize(ToNeko.java:38)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.get(Object)" because "current" is null
	at knot//org.cneko.ctlib.common.file.YamlConfiguration.get(YamlConfiguration.java:47)
	at knot//org.cneko.ctlib.common.file.YamlConfiguration.isSet(YamlConfiguration.java:125)
	at knot//org.cneko.ctlib.common.file.YamlConfiguration.contains(YamlConfiguration.java:129)
	at knot//org.cneko.toneko.common.util.ConfigBuilder.build(ConfigBuilder.java:85)
	at knot//org.cneko.toneko.common.util.ConfigUtil.<clinit>(ConfigUtil.java:33)
	... 9 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at knot//net.minecraft.class_310.<init>(class_310.java:477)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:高级 Windows 32 基本 API:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:用户体验控件库:6.10 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS 客户端 API DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.22621.4036 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP 帮助程序 API:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT 基本 API 客户端 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT 基本 API 客户端 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:电源配置文件帮助程序 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows 性能数据助手 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:远程过程调用运行时:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell 公用 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		SangforNspX64.dll:TODO: <File description>:7,5,1,1:TODO: <Company name>
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:多用户 Windows 用户 API 客户端 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP 服务:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32 位 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:应用程序兼容性客户端库:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		bcrypt.dll:Windows 加密基元库:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:用于 Windows 的 Microsoft COM:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		extnet.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		fwpuclnt.dll:FWP/IPsec 用户模式 API:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		instrument.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		java.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		java.exe:OpenJDK Platform binary:21.0.3.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jli.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jna2808453271026879181.dll:JNA native library:7.0.0:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:21.0.3.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.22621.3374 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.22621.2506 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 服务提供程序:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:电子邮件命名填充提供程序:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nio.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.22621.3672 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT 层 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		ole32.dll:用于 Windows 的 Microsoft OLE:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows 系统性能对象 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		pnrpnsp.dll:PNRP 命名空间提供程序:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.22621.3527 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:外壳简易实用工具库:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.22621.3593 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
		win32u.dll:Win32u:10.0.22621.4037 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.22621.1 (WinBuild.160101.0800):Microsoft Corporation
		wintypes.dll:Windows 基本类型 DLL:10.0.22621.4315 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.22621.3958 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:21.0.3.0:Microsoft
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 298477560 bytes (284 MiB) / 570425344 bytes (544 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900HS with Radeon Graphics        
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.29
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc.
	Graphics card #0 VRAM (MiB): 512.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 30.0.14018.15002
	Graphics card #1 name: NVIDIA GeForce GTX 1650 with Max-Q Design
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 4096.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 31.0.15.4680
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 4.27
	Memory slot #0 type: LPDDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 4.27
	Memory slot #1 type: LPDDR4
	Virtual memory max (MiB): 19744.34
	Virtual memory used (MiB): 12174.31
	Swap memory total (MiB): 3968.00
	Swap memory used (MiB): 31.09
	Space in storage for jna.tmpdir (MiB): available: 39557.15, total: 307199.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 39557.15, total: 307199.00
	Space in storage for io.netty.native.workdir (MiB): available: 39557.15, total: 307199.00
	Space in storage for java.io.tmpdir (MiB): available: 19869.30, total: 159990.31
	Space in storage for workdir (MiB): available: 39557.15, total: 307199.00
	JVM Flags: 11 total; -Xmx8192m -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		ctlib: ctLib 0.1.13
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		geckolib: GeckoLib 4 4.7
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.1
		toneko: toNeko 1.4.3
	Launched Version: 1.21.1-Fabric
	Launcher name: HMCL
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GFLW Platform: <error>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: zh_CN
	System encoding: UTF-8
	File encoding: GB18030
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# D:\game\Minecraft\minecraft-hmcl\.minecraft\crash-reports\crash-2024-12-16_20.04.10-client.txt

**Comment by CSneko** [comment]
先尝试删除 `config/toneko.yml`，然后再次启动看看，如果还是不行的话呢可以尝试把系统编码改为UTF-8

**Comment by Lemonfeline** [comment]
> 先尝试删除 `config/toneko.yml`，然后再次启动看看，如果还是不行的话呢可以尝试把系统编码改为UTF-8

两种方法都试过了，还是启动时崩溃...

**Comment by CSneko** [comment]
更新至[1.4.6](https://modrinth.com/mod/tonekomod/version/1.4.6)可以解决
