### ISSUE TITLE
banner1.20. 1fabricmod版冒险家猫娘无法正常放出等问题

### ISSUE THREAD

**Issue by yunqing-afeng** [CSneko/toNeko#68]
[08:34:56] [Worker-Main-5/ERROR]: Couldn't load tag c:tails as it is missing following references: #toneko:tails (from fabric)
[08:34:56] [Worker-Main-5/ERROR]: Couldn't load tag c:ears as it is missing following references: #toneko:ears (from fabric)
[08:34:56] [Worker-Main-3/ERROR]: Couldn't parse element predicates:n2u.chestmenu:1.13/nolastpage
com.google.gson.JsonSyntaxException: Unknown type 'alternative'
        at net.minecraft.world.level.storage.loot.GsonAdapterFactory$JsonAdapter.deserialize(GsonAdapterFactory.java:99) ~[server-intermediary.jar:?]
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1214) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1319) ~[gson-2.10.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:1261) ~[gson-2.10.jar:?]
        at net.minecraft.world.level.storage.loot.LootDataType.lambda$createSingleOrMultipleDeserialiser$2(LootDataType.java:82) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.storage.loot.LootDataType.deserialize(LootDataType.java:48) ~[server-intermediary.jar:?]
        at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$4(LootDataManager.java:55) ~[server-intermediary.jar:?]
        at java.util.HashMap.forEach(HashMap.java:1429) ~[?:?]
        at net.minecraft.world.level.storage.loot.LootDataManager.lambda$scheduleElementParse$5(LootDataManager.java:55) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
服务器核心：banner
服务器版本：1.20.1
服务器类型：fabric混端
mod版本：toNekoMod 1.3.10-1.20/toNekoMod 1.3.11 for 1.20

**Comment by CSneko** [comment]
不用管这个哦，这不会导致任何问题
