### ISSUE TITLE
一个我也不知道是什么情况的问题（也许是兼容问题）

### ISSUE THREAD

**Issue by ikunsz666** [CSneko/toNeko#7]
f[20:28:04 INFO]: [Yum] [Yum 事件监控] 插件 toNeko 处理 PlayerChatEvent 事件时发生异常!
�[20:28:04 INFO]: [Yum] 异常名称: java.lang.NoSuchMethodError
[20:28:04 INFO]: [Yum] 异常说明: 'java.lang.String com.crystalneko.ctlib.chat.chatPrefix.getAllPublicPrefixValues()'
1[20:28:04 INFO]: [Yum] 简易错误信息如下:
b[20:28:04 INFO]: [Yum]     位于 com.crystalneko.toneko.chat.nekoed.onPlayerChat(nekoed.java:36)
c[20:28:04 INFO]: [Yum]     位于 jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(未知:-2)
b[20:28:04 INFO]: [Yum]     位于 jdk.internal.reflect.NativeMethodAccessorImpl.invoke(未知:-1)
f[20:28:04 INFO]: [Yum]     位于 jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(未知:-1)
M[20:28:04 INFO]: [Yum]     位于 java.lang.reflect.Method.invoke(未知:-1)

除了yum这个简易错误信息之外无任何其他报错

服务端：Mohist（混合端）
完整日志请看粘贴：https://mclo.gs/D1Dcs0P

**Comment by CSneko** [comment]
这个应该是前置插件ctLib没有安装的原因，可以试试从[这里下载ctLib](https://githu.com/csneko/ctlib)，或许可以解决这个问题

**Comment by ikunsz666** [comment]
已经在plugins里面装入了ctLib，日志中也有一句Loading ctLib字样 但还是不行

**Comment by ikunsz666** [comment]
怀疑是ctLib没加载？

**Comment by CSneko** [comment]
可能是版本问题，因为这个类仅在最新的ctLib才存在

**Comment by ikunsz666** [comment]
我是下载的github里的最新版本 仍然是有这个错误

**Comment by CSneko** [comment]
那么很有可能是没有正常加载导致的，没有在混合端进行过测试，你可以试试使用纯净端

**Comment by ikunsz666** [comment]
好像是因为sql没连接 我有好多插件都是有sql数据库，会不会是端口冲突之类的

**Comment by ikunsz666** [comment]
发现了，问题出在ctLib上
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because "com.crystalneko.ctlib.sql.mysql.mysqlconnection" is null
        at com.crystalneko.ctlib.sql.mysql.checkColumnExists(mysql.java:261) ~[?:?]
        at com.crystalneko.ctlib.sql.mysql.addColumn(mysql.java:247) ~[?:?]
        at com.crystalneko.ctlib.ecomony.playerEcomony.addSqliteColum(playerEcomony.java:94) ~[?:?]
        at com.crystalneko.ctlib.ecomony.playerEcomony.<init>(playerEcomony.java:15) ~[?:?]
        at com.crystalneko.ctlib.CtLib.onEnable(CtLib.java:37) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:347) ~[forge-1.20.1-47.1.79-universal.jar%23257!/:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[forge-1.20.1-47.1.79-universal.jar%23257!/:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:482) ~[forge-1.20.1-47.1.79-universal.jar%23257!/:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:548) ~[forge-1.20.1-47.1.79-universal.jar%23257!/:997de31d-ddc9a2dad-d2eba2c8-47.2.1]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:461) ~[forge-1.20.1-47.1.79-universal.jar%23257!/:997de31d-ddc9a2dad-d2eba2c8-47.2.1]
        at net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:441) ~[server-1.20.1-20230612.114412-srg.jar%23252!/:?]
        at net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23252!/:?]
        at net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:219) ~[server-1.20.1-20230612.114412-srg.jar%23252!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:850) ~[server-1.20.1-20230612.114412-srg.jar%23252!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23252!/:?]
mysql没连接吗？我在配置文件里我记得是启用了诶

**Comment by CSneko** [comment]
就是没连接上，可能是数据库账户密码啥的错了，不过toNeko插件用不到mysql，因此可以设置为false
