### ISSUE TITLE
两个bug：永恒猫娘和可叠加猫娘

### ISSUE THREAD

**Issue by lyy2182** [CSneko/toNeko#8]
环境:
Windows 11
java version "20.0.2" 2023-07-18
Java(TM) SE Runtime Environment (build 20.0.2+9-78)
Java HotSpot(TM) 64-Bit Server VM (build 20.0.2+9-78, mixed mode, sharing)
服务端: 原版Bukkit以及BukkitSpigot

把自己设置成猫娘后再remove会获得一个[null]前缀
再在[null]的基础上再把自己设置成猫娘就可以触发永恒猫娘 表现为无法remove 服务器后台显示:
[20:50:28] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tocat' in plugin toNeko v0.0.5
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[bukkit-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[bukkit-1.20.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.CraftServer.dispatchCommand(CraftServer.java:858) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at org.bukkit.craftbukkit.v1_20_R2.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:50) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.commands.CommandDispatcher.performCommand(CommandDispatcher.java:320) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.commands.CommandDispatcher.a(CommandDispatcher.java:304) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1791) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.network.PlayerConnection.lambda$15(PlayerConnection.java:1753) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.util.thread.IAsyncTaskHandler.b(SourceFile:67) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1092) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1071) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1064) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.u_(MinecraftServer.java:1048) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:966) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:290) ~[craftbukkit-1.20.2-R0.1-SNAPSHOT.jar:3904-Bukkit-1bf30a4]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "arr[i]" is null
        at com.crystalneko.ctlib.chat.chatPrefix.deleteValue(chatPrefix.java:116) ~[?:?]
        at com.crystalneko.ctlib.chat.chatPrefix.subPrivatePrefix(chatPrefix.java:68) ~[?:?]
        at com.crystalneko.toneko.command.ToNekoCommand.onCommand(ToNekoCommand.java:90) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[bukkit-1.20.2-R0.1-SNAPSHOT.jar:?]
        ... 23 more

触发永恒猫娘后反复重进服务器就会叠加猫娘头衔 重进几次就叠加几次
重新启动服务端就会恢复正常

演示视频:
https://nps.lanzouj.com/iu2vc1atmo7e

**Comment by CSneko** [comment]
这个问题应该主要出在了ctLib上，你可以尝试下更换到最新版本的ctLib和toNeko，ctLib我发布了几个有严重Bug的版本，尽管我后来将其修复，但是不确定的是自动下载的ctLib为无严重Bug的版本，因为自动下载的源不是来自于github，而是来自于https://w.csk.asia/res/plugins/ctLib.jar，这里版本并非一定是最新的，如果更新后问题依然存在，我会考虑修复

**Comment by CSneko** [comment]
问题已解决，解决方法:
更新ctLib
