### ISSUE TITLE
前缀重复且无法移除问题

### ISSUE THREAD

**Issue by 3944Realms** [CSneko/toNeko#9]
服务器核心版本：git-Purpur-2086 (MC: 1.20.2)*
![屏幕截图 2023-11-05 220847](https://github.com/CSneko/toNeko/assets/81907904/139b06ac-8d91-427b-8c91-7e92d4387fb5)

后台日志：
[21:53:20 INFO]: [扫地娘] 即将清理掉落物，倒计时 120 秒
[21:53:29 INFO]: XiaoWangZi_Dawn issued server command: /enderchest
[21:54:20 INFO]: [扫地娘] 即将清理掉落物，倒计时 60 秒
[21:54:50 INFO]: [扫地娘] 即将清理掉落物，倒计时 30 秒
[21:55:00 INFO]: [扫地娘] 即将清理掉落物，倒计时 20 秒
[21:55:10 INFO]: [扫地娘] 即将清理掉落物，倒计时 10 秒
[21:55:13 INFO]: [Not Secure] [猫娘][猫娘][猫娘][猫娘][猫娘][猫娘][猫娘][猫娘][猫娘][猫娘]3944Realms >> 看github刚刚
[21:55:17 INFO]: [扫地娘] 即将清理掉落物，倒计时 3 秒
[21:55:17 ERROR]: Could not pass event PlayerChatEvent to toNeko v0.0.8
java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0
?
^
        at java.util.regex.Pattern.error(Pattern.java:2028) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2203) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2069) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1783) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1430) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1069) ~[?:?]
        at java.lang.String.replaceAll(String.java:2944) ~[?:?]
        at com.crystalneko.toneko.chat.nekoed.replaceBlocks(nekoed.java:128) ~[toNeko-0.0.8.jar:?]
        at com.crystalneko.toneko.chat.nekoed.onPlayerChat(nekoed.java:62) ~[toNeko-0.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2086]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.adventure.ChatProcessor$1.evaluate(ChatProcessor.java:109) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.adventure.ChatProcessor$1.evaluate(ChatProcessor.java:106) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.util.Waitable.run(Waitable.java:23) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1525) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[21:55:17 INFO]: [Not Secure] <XiaoWangZi_Dawn> 金子不太够，节点
[21:55:18 INFO]: [扫地娘] 即将清理掉落物，倒计时 2 秒
[21:55:19 INFO]: [扫地娘] 即将清理掉落物，倒计时 1 秒
[21:55:20 INFO]: [扫地娘] 清理完毕, 共计清理 7 个掉落物.
[21:55:28 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:29 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:29 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:30 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:30 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:31 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:31 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:32 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:32 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:32 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:33 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:33 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:34 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:37 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:38 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:39 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:41 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:42 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:43 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:44 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:45 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:46 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:47 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:48 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:49 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:50 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:51 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:53 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:54 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:55 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:56 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:57 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:55:59 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:00 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:01 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:02 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:03 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:04 INFO]: XiaoWangZi_Dawn issued server command: /toneko remove 3944Realms
[21:56:21 ERROR]: Could not pass event PlayerChatEvent to toNeko v0.0.8
java.util.regex.PatternSyntaxException: Dangling meta character '?' near index 0
?
^
        at java.util.regex.Pattern.error(Pattern.java:2028) ~[?:?]
        at java.util.regex.Pattern.sequence(Pattern.java:2203) ~[?:?]
        at java.util.regex.Pattern.expr(Pattern.java:2069) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1783) ~[?:?]
        at java.util.regex.Pattern.<init>(Pattern.java:1430) ~[?:?]
        at java.util.regex.Pattern.compile(Pattern.java:1069) ~[?:?]
        at java.lang.String.replaceAll(String.java:2944) ~[?:?]
        at com.crystalneko.toneko.chat.nekoed.replaceBlocks(nekoed.java:128) ~[toNeko-0.0.8.jar:?]
        at com.crystalneko.toneko.chat.nekoed.onPlayerChat(nekoed.java:62) ~[toNeko-0.0.8.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor172.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:git-Purpur-2086]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.2-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.adventure.ChatProcessor.post(ChatProcessor.java:416) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.adventure.ChatProcessor$1.evaluate(ChatProcessor.java:109) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at io.papermc.paper.adventure.ChatProcessor$1.evaluate(ChatProcessor.java:106) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at org.bukkit.craftbukkit.v1_20_R2.util.Waitable.run(Waitable.java:23) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1525) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-2086]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
[21:56:21 INFO]: [Not Secure] <XiaoWangZi_Dawn> 删干净了，再说话试试
![屏幕截图 2023-11-05 221144](https://github.com/CSneko/toNeko/assets/81907904/2cbc7eac-4841-4187-bdbf-1bee0ce7986d)

**Comment by CSneko** [comment]
明白，正在修复

**Comment by CSneko** [comment]
问题已解决，解决方法:
更新[ctLib](https://github.com/csneko/ctlib)
